# Generated by Django 4.2 on 2023-04-08 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_announcement_cost_announcement_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='description',
            field=models.TextField(default='Описание'),
        ),
    ]
